//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.04 at 05:39:40 AM UTC 
//


package com.firstdata.cmpwsapi.schemas.cmpmsg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AF complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AF"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ZipCodeMatchIndicator" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}MatchValues"/&gt;
 *         &lt;element name="StreetMatchIndicator" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}MatchValues"/&gt;
 *         &lt;element name="NameMatchIndicator" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}MatchValuesAF"/&gt;
 *         &lt;element name="TelephoneMatchIndicator" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}MatchValues"/&gt;
 *         &lt;element name="EmailMatchIndicator" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}MatchValues"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AF", propOrder = {
    "zipCodeMatchIndicator",
    "streetMatchIndicator",
    "nameMatchIndicator",
    "telephoneMatchIndicator",
    "emailMatchIndicator"
})
public class AF {

    @XmlElement(name = "ZipCodeMatchIndicator", required = true)
    protected String zipCodeMatchIndicator;
    @XmlElement(name = "StreetMatchIndicator", required = true)
    protected String streetMatchIndicator;
    @XmlElement(name = "NameMatchIndicator", required = true)
    protected String nameMatchIndicator;
    @XmlElement(name = "TelephoneMatchIndicator", required = true)
    protected String telephoneMatchIndicator;
    @XmlElement(name = "EmailMatchIndicator", required = true)
    protected String emailMatchIndicator;

    /**
     * Gets the value of the zipCodeMatchIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZipCodeMatchIndicator() {
        return zipCodeMatchIndicator;
    }

    /**
     * Sets the value of the zipCodeMatchIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZipCodeMatchIndicator(String value) {
        this.zipCodeMatchIndicator = value;
    }

    /**
     * Gets the value of the streetMatchIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetMatchIndicator() {
        return streetMatchIndicator;
    }

    /**
     * Sets the value of the streetMatchIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetMatchIndicator(String value) {
        this.streetMatchIndicator = value;
    }

    /**
     * Gets the value of the nameMatchIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameMatchIndicator() {
        return nameMatchIndicator;
    }

    /**
     * Sets the value of the nameMatchIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameMatchIndicator(String value) {
        this.nameMatchIndicator = value;
    }

    /**
     * Gets the value of the telephoneMatchIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelephoneMatchIndicator() {
        return telephoneMatchIndicator;
    }

    /**
     * Sets the value of the telephoneMatchIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelephoneMatchIndicator(String value) {
        this.telephoneMatchIndicator = value;
    }

    /**
     * Gets the value of the emailMatchIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailMatchIndicator() {
        return emailMatchIndicator;
    }

    /**
     * Sets the value of the emailMatchIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailMatchIndicator(String value) {
        this.emailMatchIndicator = value;
    }

}
