//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.04 at 05:39:40 AM UTC 
//


package com.firstdata.cmpwsapi.schemas.cmpmsg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillToTelephone complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillToTelephone"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LT" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}LT"/&gt;
 *         &lt;element name="LA" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}ContactAddressWOTel"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillToTelephone", propOrder = {
    "lt",
    "la"
})
public class BillToTelephone {

    @XmlElement(name = "LT", required = true)
    protected LT lt;
    @XmlElement(name = "LA", required = true)
    protected ContactAddressWOTel la;

    /**
     * Gets the value of the lt property.
     * 
     * @return
     *     possible object is
     *     {@link LT }
     *     
     */
    public LT getLT() {
        return lt;
    }

    /**
     * Sets the value of the lt property.
     * 
     * @param value
     *     allowed object is
     *     {@link LT }
     *     
     */
    public void setLT(LT value) {
        this.lt = value;
    }

    /**
     * Gets the value of the la property.
     * 
     * @return
     *     possible object is
     *     {@link ContactAddressWOTel }
     *     
     */
    public ContactAddressWOTel getLA() {
        return la;
    }

    /**
     * Sets the value of the la property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactAddressWOTel }
     *     
     */
    public void setLA(ContactAddressWOTel value) {
        this.la = value;
    }

}
