//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.04 at 05:39:40 AM UTC 
//


package com.firstdata.cmpwsapi.schemas.cmpmsg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BM"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ExpirationDate"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="4"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CreditLine"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="12"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PromoOffer"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="8"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ApprovedAmount"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[0-9]{0,12}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ApprovedTermCode"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="8"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ShippingAddressIndicator"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LTVEstimator"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="8"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RiskEstimator"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="8"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RiskQueueAssignment"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="8"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LeaseMasterAgreementID"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="10"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LeaseDocumentationRequirement"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="12"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BM", propOrder = {
    "expirationDate",
    "creditLine",
    "promoOffer",
    "approvedAmount",
    "approvedTermCode",
    "shippingAddressIndicator",
    "ltvEstimator",
    "riskEstimator",
    "riskQueueAssignment",
    "leaseMasterAgreementID",
    "leaseDocumentationRequirement"
})
public class BM {

    @XmlElement(name = "ExpirationDate", required = true)
    protected String expirationDate;
    @XmlElement(name = "CreditLine", required = true)
    protected String creditLine;
    @XmlElement(name = "PromoOffer", required = true)
    protected String promoOffer;
    @XmlElement(name = "ApprovedAmount", required = true)
    protected String approvedAmount;
    @XmlElement(name = "ApprovedTermCode", required = true)
    protected String approvedTermCode;
    @XmlElement(name = "ShippingAddressIndicator", required = true)
    protected String shippingAddressIndicator;
    @XmlElement(name = "LTVEstimator", required = true)
    protected String ltvEstimator;
    @XmlElement(name = "RiskEstimator", required = true)
    protected String riskEstimator;
    @XmlElement(name = "RiskQueueAssignment", required = true)
    protected String riskQueueAssignment;
    @XmlElement(name = "LeaseMasterAgreementID", required = true)
    protected String leaseMasterAgreementID;
    @XmlElement(name = "LeaseDocumentationRequirement", required = true)
    protected String leaseDocumentationRequirement;

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpirationDate(String value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the creditLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditLine() {
        return creditLine;
    }

    /**
     * Sets the value of the creditLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditLine(String value) {
        this.creditLine = value;
    }

    /**
     * Gets the value of the promoOffer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromoOffer() {
        return promoOffer;
    }

    /**
     * Sets the value of the promoOffer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromoOffer(String value) {
        this.promoOffer = value;
    }

    /**
     * Gets the value of the approvedAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovedAmount() {
        return approvedAmount;
    }

    /**
     * Sets the value of the approvedAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovedAmount(String value) {
        this.approvedAmount = value;
    }

    /**
     * Gets the value of the approvedTermCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovedTermCode() {
        return approvedTermCode;
    }

    /**
     * Sets the value of the approvedTermCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovedTermCode(String value) {
        this.approvedTermCode = value;
    }

    /**
     * Gets the value of the shippingAddressIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShippingAddressIndicator() {
        return shippingAddressIndicator;
    }

    /**
     * Sets the value of the shippingAddressIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShippingAddressIndicator(String value) {
        this.shippingAddressIndicator = value;
    }

    /**
     * Gets the value of the ltvEstimator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLTVEstimator() {
        return ltvEstimator;
    }

    /**
     * Sets the value of the ltvEstimator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLTVEstimator(String value) {
        this.ltvEstimator = value;
    }

    /**
     * Gets the value of the riskEstimator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRiskEstimator() {
        return riskEstimator;
    }

    /**
     * Sets the value of the riskEstimator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRiskEstimator(String value) {
        this.riskEstimator = value;
    }

    /**
     * Gets the value of the riskQueueAssignment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRiskQueueAssignment() {
        return riskQueueAssignment;
    }

    /**
     * Sets the value of the riskQueueAssignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRiskQueueAssignment(String value) {
        this.riskQueueAssignment = value;
    }

    /**
     * Gets the value of the leaseMasterAgreementID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeaseMasterAgreementID() {
        return leaseMasterAgreementID;
    }

    /**
     * Sets the value of the leaseMasterAgreementID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeaseMasterAgreementID(String value) {
        this.leaseMasterAgreementID = value;
    }

    /**
     * Gets the value of the leaseDocumentationRequirement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeaseDocumentationRequirement() {
        return leaseDocumentationRequirement;
    }

    /**
     * Sets the value of the leaseDocumentationRequirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeaseDocumentationRequirement(String value) {
        this.leaseDocumentationRequirement = value;
    }

}
