//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.04 at 05:39:40 AM UTC 
//


package com.firstdata.cmpwsapi.schemas.cmpmsg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CRRES complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CRRES"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CryptogramValidationServiceIndicatorFlag" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Y"/&gt;
 *               &lt;enumeration value="N"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="MerchantOnBehalfServiceValue" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="53"/&gt;
 *               &lt;enumeration value="54"/&gt;
 *               &lt;enumeration value="56"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="MerchantOnBehalfResult" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="A"/&gt;
 *               &lt;enumeration value="E"/&gt;
 *               &lt;enumeration value="F"/&gt;
 *               &lt;enumeration value="I"/&gt;
 *               &lt;enumeration value="K"/&gt;
 *               &lt;enumeration value="U"/&gt;
 *               &lt;enumeration value="V"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CRRES", propOrder = {
    "cryptogramValidationServiceIndicatorFlag",
    "merchantOnBehalfServiceValue",
    "merchantOnBehalfResult"
})
public class CRRES {

    @XmlElement(name = "CryptogramValidationServiceIndicatorFlag")
    protected String cryptogramValidationServiceIndicatorFlag;
    @XmlElement(name = "MerchantOnBehalfServiceValue")
    protected String merchantOnBehalfServiceValue;
    @XmlElement(name = "MerchantOnBehalfResult")
    protected String merchantOnBehalfResult;

    /**
     * Gets the value of the cryptogramValidationServiceIndicatorFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCryptogramValidationServiceIndicatorFlag() {
        return cryptogramValidationServiceIndicatorFlag;
    }

    /**
     * Sets the value of the cryptogramValidationServiceIndicatorFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCryptogramValidationServiceIndicatorFlag(String value) {
        this.cryptogramValidationServiceIndicatorFlag = value;
    }

    /**
     * Gets the value of the merchantOnBehalfServiceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantOnBehalfServiceValue() {
        return merchantOnBehalfServiceValue;
    }

    /**
     * Sets the value of the merchantOnBehalfServiceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantOnBehalfServiceValue(String value) {
        this.merchantOnBehalfServiceValue = value;
    }

    /**
     * Gets the value of the merchantOnBehalfResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantOnBehalfResult() {
        return merchantOnBehalfResult;
    }

    /**
     * Sets the value of the merchantOnBehalfResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantOnBehalfResult(String value) {
        this.merchantOnBehalfResult = value;
    }

}
