//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.04 at 05:39:40 AM UTC 
//


package com.firstdata.cmpwsapi.schemas.cmpmsg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EAX003 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EAX003"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TransactionIdentifier"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[0-9]{0,15}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="POSCapabilityCode" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}POSCapabilityCode"/&gt;
 *         &lt;element name="CardholderAuthenticationCapability"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="0"/&gt;
 *               &lt;enumeration value="6"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CardCaptureCapability"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="0"/&gt;
 *               &lt;enumeration value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="OperatingEnvironment"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="0"/&gt;
 *               &lt;enumeration value="1"/&gt;
 *               &lt;enumeration value="2"/&gt;
 *               &lt;enumeration value="3"/&gt;
 *               &lt;enumeration value="4"/&gt;
 *               &lt;enumeration value="5"/&gt;
 *               &lt;enumeration value="9"/&gt;
 *               &lt;enumeration value="S"/&gt;
 *               &lt;enumeration value="T"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CardHolderPresent"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="0"/&gt;
 *               &lt;enumeration value="1"/&gt;
 *               &lt;enumeration value="2"/&gt;
 *               &lt;enumeration value="3"/&gt;
 *               &lt;enumeration value="4"/&gt;
 *               &lt;enumeration value="9"/&gt;
 *               &lt;enumeration value="S"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CardPresent"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="0"/&gt;
 *               &lt;enumeration value="1"/&gt;
 *               &lt;enumeration value="W"/&gt;
 *               &lt;enumeration value="Z"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="POSEntryMode" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}POSEntryMode1"/&gt;
 *         &lt;element name="POSCardIDMethod" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}POSCardIDMethod1"/&gt;
 *         &lt;element name="CardholderAuthenticationEntity"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="0"/&gt;
 *               &lt;enumeration value="1"/&gt;
 *               &lt;enumeration value="2"/&gt;
 *               &lt;enumeration value="4"/&gt;
 *               &lt;enumeration value="5"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CardDataOutputCapability"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="0"/&gt;
 *               &lt;enumeration value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TerminalOutputCapability"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="0"/&gt;
 *               &lt;enumeration value="1"/&gt;
 *               &lt;enumeration value="2"/&gt;
 *               &lt;enumeration value="3"/&gt;
 *               &lt;enumeration value="4"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PINCaptureCapability"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="0"/&gt;
 *               &lt;enumeration value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AuthorizedAmount" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[0-9]{0,12}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Reserved" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="74"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EAX003", propOrder = {
    "transactionIdentifier",
    "posCapabilityCode",
    "cardholderAuthenticationCapability",
    "cardCaptureCapability",
    "operatingEnvironment",
    "cardHolderPresent",
    "cardPresent",
    "posEntryMode",
    "posCardIDMethod",
    "cardholderAuthenticationEntity",
    "cardDataOutputCapability",
    "terminalOutputCapability",
    "pinCaptureCapability",
    "authorizedAmount",
    "reserved"
})
public class EAX003 {

    @XmlElement(name = "TransactionIdentifier", required = true)
    protected String transactionIdentifier;
    @XmlElement(name = "POSCapabilityCode", required = true)
    protected String posCapabilityCode;
    @XmlElement(name = "CardholderAuthenticationCapability", required = true)
    protected String cardholderAuthenticationCapability;
    @XmlElement(name = "CardCaptureCapability", required = true)
    protected String cardCaptureCapability;
    @XmlElement(name = "OperatingEnvironment", required = true)
    protected String operatingEnvironment;
    @XmlElement(name = "CardHolderPresent", required = true)
    protected String cardHolderPresent;
    @XmlElement(name = "CardPresent", required = true)
    protected String cardPresent;
    @XmlElement(name = "POSEntryMode", required = true)
    protected String posEntryMode;
    @XmlElement(name = "POSCardIDMethod", required = true)
    protected String posCardIDMethod;
    @XmlElement(name = "CardholderAuthenticationEntity", required = true)
    protected String cardholderAuthenticationEntity;
    @XmlElement(name = "CardDataOutputCapability", required = true)
    protected String cardDataOutputCapability;
    @XmlElement(name = "TerminalOutputCapability", required = true)
    protected String terminalOutputCapability;
    @XmlElement(name = "PINCaptureCapability", required = true)
    protected String pinCaptureCapability;
    @XmlElement(name = "AuthorizedAmount")
    protected String authorizedAmount;
    @XmlElement(name = "Reserved")
    protected String reserved;

    /**
     * Gets the value of the transactionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionIdentifier() {
        return transactionIdentifier;
    }

    /**
     * Sets the value of the transactionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionIdentifier(String value) {
        this.transactionIdentifier = value;
    }

    /**
     * Gets the value of the posCapabilityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSCapabilityCode() {
        return posCapabilityCode;
    }

    /**
     * Sets the value of the posCapabilityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSCapabilityCode(String value) {
        this.posCapabilityCode = value;
    }

    /**
     * Gets the value of the cardholderAuthenticationCapability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardholderAuthenticationCapability() {
        return cardholderAuthenticationCapability;
    }

    /**
     * Sets the value of the cardholderAuthenticationCapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardholderAuthenticationCapability(String value) {
        this.cardholderAuthenticationCapability = value;
    }

    /**
     * Gets the value of the cardCaptureCapability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardCaptureCapability() {
        return cardCaptureCapability;
    }

    /**
     * Sets the value of the cardCaptureCapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardCaptureCapability(String value) {
        this.cardCaptureCapability = value;
    }

    /**
     * Gets the value of the operatingEnvironment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatingEnvironment() {
        return operatingEnvironment;
    }

    /**
     * Sets the value of the operatingEnvironment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatingEnvironment(String value) {
        this.operatingEnvironment = value;
    }

    /**
     * Gets the value of the cardHolderPresent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardHolderPresent() {
        return cardHolderPresent;
    }

    /**
     * Sets the value of the cardHolderPresent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardHolderPresent(String value) {
        this.cardHolderPresent = value;
    }

    /**
     * Gets the value of the cardPresent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardPresent() {
        return cardPresent;
    }

    /**
     * Sets the value of the cardPresent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardPresent(String value) {
        this.cardPresent = value;
    }

    /**
     * Gets the value of the posEntryMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSEntryMode() {
        return posEntryMode;
    }

    /**
     * Sets the value of the posEntryMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSEntryMode(String value) {
        this.posEntryMode = value;
    }

    /**
     * Gets the value of the posCardIDMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSCardIDMethod() {
        return posCardIDMethod;
    }

    /**
     * Sets the value of the posCardIDMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSCardIDMethod(String value) {
        this.posCardIDMethod = value;
    }

    /**
     * Gets the value of the cardholderAuthenticationEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardholderAuthenticationEntity() {
        return cardholderAuthenticationEntity;
    }

    /**
     * Sets the value of the cardholderAuthenticationEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardholderAuthenticationEntity(String value) {
        this.cardholderAuthenticationEntity = value;
    }

    /**
     * Gets the value of the cardDataOutputCapability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardDataOutputCapability() {
        return cardDataOutputCapability;
    }

    /**
     * Sets the value of the cardDataOutputCapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardDataOutputCapability(String value) {
        this.cardDataOutputCapability = value;
    }

    /**
     * Gets the value of the terminalOutputCapability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalOutputCapability() {
        return terminalOutputCapability;
    }

    /**
     * Sets the value of the terminalOutputCapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalOutputCapability(String value) {
        this.terminalOutputCapability = value;
    }

    /**
     * Gets the value of the pinCaptureCapability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPINCaptureCapability() {
        return pinCaptureCapability;
    }

    /**
     * Sets the value of the pinCaptureCapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPINCaptureCapability(String value) {
        this.pinCaptureCapability = value;
    }

    /**
     * Gets the value of the authorizedAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizedAmount() {
        return authorizedAmount;
    }

    /**
     * Sets the value of the authorizedAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizedAmount(String value) {
        this.authorizedAmount = value;
    }

    /**
     * Gets the value of the reserved property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReserved() {
        return reserved;
    }

    /**
     * Sets the value of the reserved property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReserved(String value) {
        this.reserved = value;
    }

}
