//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.04 at 05:39:40 AM UTC 
//


package com.firstdata.cmpwsapi.schemas.cmpmsg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EMC002 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EMC002"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AccountholderAuthenticationValue"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="32"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AuthType" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="0"/&gt;
 *               &lt;enumeration value="1"/&gt;
 *               &lt;enumeration value=" "/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="MasterPassInd" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="N"/&gt;
 *               &lt;enumeration value="U"/&gt;
 *               &lt;enumeration value="S"/&gt;
 *               &lt;enumeration value="A"/&gt;
 *               &lt;enumeration value="I"/&gt;
 *               &lt;enumeration value="M"/&gt;
 *               &lt;enumeration value=" "/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="WalletProgID" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="101"/&gt;
 *               &lt;enumeration value="102"/&gt;
 *               &lt;enumeration value=" "/&gt;
 *               &lt;enumeration value="103"/&gt;
 *               &lt;enumeration value="216"/&gt;
 *               &lt;enumeration value="217"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CryptogramValidationServiceIndicatorFlag" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Y"/&gt;
 *               &lt;enumeration value="N"/&gt;
 *               &lt;enumeration value=" "/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DowngradeReasonRequestIndicatorFlag" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Y"/&gt;
 *               &lt;enumeration value="N"/&gt;
 *               &lt;enumeration value=" "/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Reserved" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="75"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EMC002", propOrder = {
    "accountholderAuthenticationValue",
    "authType",
    "masterPassInd",
    "walletProgID",
    "cryptogramValidationServiceIndicatorFlag",
    "downgradeReasonRequestIndicatorFlag",
    "reserved"
})
public class EMC002 {

    @XmlElement(name = "AccountholderAuthenticationValue", required = true)
    protected String accountholderAuthenticationValue;
    @XmlElement(name = "AuthType")
    protected String authType;
    @XmlElement(name = "MasterPassInd")
    protected String masterPassInd;
    @XmlElement(name = "WalletProgID")
    protected String walletProgID;
    @XmlElement(name = "CryptogramValidationServiceIndicatorFlag")
    protected String cryptogramValidationServiceIndicatorFlag;
    @XmlElement(name = "DowngradeReasonRequestIndicatorFlag")
    protected String downgradeReasonRequestIndicatorFlag;
    @XmlElement(name = "Reserved")
    protected String reserved;

    /**
     * Gets the value of the accountholderAuthenticationValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountholderAuthenticationValue() {
        return accountholderAuthenticationValue;
    }

    /**
     * Sets the value of the accountholderAuthenticationValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountholderAuthenticationValue(String value) {
        this.accountholderAuthenticationValue = value;
    }

    /**
     * Gets the value of the authType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthType() {
        return authType;
    }

    /**
     * Sets the value of the authType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthType(String value) {
        this.authType = value;
    }

    /**
     * Gets the value of the masterPassInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasterPassInd() {
        return masterPassInd;
    }

    /**
     * Sets the value of the masterPassInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterPassInd(String value) {
        this.masterPassInd = value;
    }

    /**
     * Gets the value of the walletProgID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWalletProgID() {
        return walletProgID;
    }

    /**
     * Sets the value of the walletProgID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWalletProgID(String value) {
        this.walletProgID = value;
    }

    /**
     * Gets the value of the cryptogramValidationServiceIndicatorFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCryptogramValidationServiceIndicatorFlag() {
        return cryptogramValidationServiceIndicatorFlag;
    }

    /**
     * Sets the value of the cryptogramValidationServiceIndicatorFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCryptogramValidationServiceIndicatorFlag(String value) {
        this.cryptogramValidationServiceIndicatorFlag = value;
    }

    /**
     * Gets the value of the downgradeReasonRequestIndicatorFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDowngradeReasonRequestIndicatorFlag() {
        return downgradeReasonRequestIndicatorFlag;
    }

    /**
     * Sets the value of the downgradeReasonRequestIndicatorFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDowngradeReasonRequestIndicatorFlag(String value) {
        this.downgradeReasonRequestIndicatorFlag = value;
    }

    /**
     * Gets the value of the reserved property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReserved() {
        return reserved;
    }

    /**
     * Sets the value of the reserved property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReserved(String value) {
        this.reserved = value;
    }

}
