//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.04 at 05:39:40 AM UTC 
//


package com.firstdata.cmpwsapi.schemas.cmpmsg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EVI001 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EVI001"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="POSCapabilityCode" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}POSCapabilityCode"/&gt;
 *         &lt;element name="POSEntryMode" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}POSEntryMode2"/&gt;
 *         &lt;element name="POSAuthorizationSourceCode" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}POSAuthorizationSource"/&gt;
 *         &lt;element name="POSCardIDMethod" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}POSCardIDMethod2"/&gt;
 *         &lt;element name="AuthorizationCharacteristicIndicator" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}AuthorizationCharacteristicIndicator"/&gt;
 *         &lt;element name="TransactionIdentifier"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[0-9]{0,15}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ValidationCode"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="4"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AuthorizeAmount"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[0-9]{0,12}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="MCC" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[0-9]{0,4}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TotalAuthorizeAmount"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[0-9]{0,12}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="MarketSpecificDataIndicator"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="B"/&gt;
 *               &lt;enumeration value="H"/&gt;
 *               &lt;enumeration value=" "/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Reserved1" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CardLevelResult"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Reserved2" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SpendQualifiedInd" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TokenAssuranceLevel" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Reserved" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="53"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EVI001", propOrder = {
    "posCapabilityCode",
    "posEntryMode",
    "posAuthorizationSourceCode",
    "posCardIDMethod",
    "authorizationCharacteristicIndicator",
    "transactionIdentifier",
    "validationCode",
    "authorizeAmount",
    "mcc",
    "totalAuthorizeAmount",
    "marketSpecificDataIndicator",
    "reserved1",
    "cardLevelResult",
    "reserved2",
    "spendQualifiedInd",
    "tokenAssuranceLevel",
    "reserved"
})
public class EVI001 {

    @XmlElement(name = "POSCapabilityCode", required = true)
    protected String posCapabilityCode;
    @XmlElement(name = "POSEntryMode", required = true)
    protected String posEntryMode;
    @XmlElement(name = "POSAuthorizationSourceCode", required = true)
    protected String posAuthorizationSourceCode;
    @XmlElement(name = "POSCardIDMethod", required = true)
    protected String posCardIDMethod;
    @XmlElement(name = "AuthorizationCharacteristicIndicator", required = true)
    @XmlSchemaType(name = "string")
    protected AuthorizationCharacteristicIndicator authorizationCharacteristicIndicator;
    @XmlElement(name = "TransactionIdentifier", required = true)
    protected String transactionIdentifier;
    @XmlElement(name = "ValidationCode", required = true)
    protected String validationCode;
    @XmlElement(name = "AuthorizeAmount", required = true)
    protected String authorizeAmount;
    @XmlElement(name = "MCC")
    protected String mcc;
    @XmlElement(name = "TotalAuthorizeAmount", required = true)
    protected String totalAuthorizeAmount;
    @XmlElement(name = "MarketSpecificDataIndicator", required = true)
    protected String marketSpecificDataIndicator;
    @XmlElement(name = "Reserved1")
    protected String reserved1;
    @XmlElement(name = "CardLevelResult", required = true)
    protected String cardLevelResult;
    @XmlElement(name = "Reserved2")
    protected String reserved2;
    @XmlElement(name = "SpendQualifiedInd")
    protected String spendQualifiedInd;
    @XmlElement(name = "TokenAssuranceLevel")
    protected String tokenAssuranceLevel;
    @XmlElement(name = "Reserved")
    protected String reserved;

    /**
     * Gets the value of the posCapabilityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSCapabilityCode() {
        return posCapabilityCode;
    }

    /**
     * Sets the value of the posCapabilityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSCapabilityCode(String value) {
        this.posCapabilityCode = value;
    }

    /**
     * Gets the value of the posEntryMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSEntryMode() {
        return posEntryMode;
    }

    /**
     * Sets the value of the posEntryMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSEntryMode(String value) {
        this.posEntryMode = value;
    }

    /**
     * Gets the value of the posAuthorizationSourceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSAuthorizationSourceCode() {
        return posAuthorizationSourceCode;
    }

    /**
     * Sets the value of the posAuthorizationSourceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSAuthorizationSourceCode(String value) {
        this.posAuthorizationSourceCode = value;
    }

    /**
     * Gets the value of the posCardIDMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSCardIDMethod() {
        return posCardIDMethod;
    }

    /**
     * Sets the value of the posCardIDMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSCardIDMethod(String value) {
        this.posCardIDMethod = value;
    }

    /**
     * Gets the value of the authorizationCharacteristicIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorizationCharacteristicIndicator }
     *     
     */
    public AuthorizationCharacteristicIndicator getAuthorizationCharacteristicIndicator() {
        return authorizationCharacteristicIndicator;
    }

    /**
     * Sets the value of the authorizationCharacteristicIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorizationCharacteristicIndicator }
     *     
     */
    public void setAuthorizationCharacteristicIndicator(AuthorizationCharacteristicIndicator value) {
        this.authorizationCharacteristicIndicator = value;
    }

    /**
     * Gets the value of the transactionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionIdentifier() {
        return transactionIdentifier;
    }

    /**
     * Sets the value of the transactionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionIdentifier(String value) {
        this.transactionIdentifier = value;
    }

    /**
     * Gets the value of the validationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidationCode() {
        return validationCode;
    }

    /**
     * Sets the value of the validationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidationCode(String value) {
        this.validationCode = value;
    }

    /**
     * Gets the value of the authorizeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizeAmount() {
        return authorizeAmount;
    }

    /**
     * Sets the value of the authorizeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizeAmount(String value) {
        this.authorizeAmount = value;
    }

    /**
     * Gets the value of the mcc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMCC() {
        return mcc;
    }

    /**
     * Sets the value of the mcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMCC(String value) {
        this.mcc = value;
    }

    /**
     * Gets the value of the totalAuthorizeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalAuthorizeAmount() {
        return totalAuthorizeAmount;
    }

    /**
     * Sets the value of the totalAuthorizeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalAuthorizeAmount(String value) {
        this.totalAuthorizeAmount = value;
    }

    /**
     * Gets the value of the marketSpecificDataIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketSpecificDataIndicator() {
        return marketSpecificDataIndicator;
    }

    /**
     * Sets the value of the marketSpecificDataIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketSpecificDataIndicator(String value) {
        this.marketSpecificDataIndicator = value;
    }

    /**
     * Gets the value of the reserved1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReserved1() {
        return reserved1;
    }

    /**
     * Sets the value of the reserved1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReserved1(String value) {
        this.reserved1 = value;
    }

    /**
     * Gets the value of the cardLevelResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardLevelResult() {
        return cardLevelResult;
    }

    /**
     * Sets the value of the cardLevelResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardLevelResult(String value) {
        this.cardLevelResult = value;
    }

    /**
     * Gets the value of the reserved2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * Sets the value of the reserved2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReserved2(String value) {
        this.reserved2 = value;
    }

    /**
     * Gets the value of the spendQualifiedInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpendQualifiedInd() {
        return spendQualifiedInd;
    }

    /**
     * Sets the value of the spendQualifiedInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpendQualifiedInd(String value) {
        this.spendQualifiedInd = value;
    }

    /**
     * Gets the value of the tokenAssuranceLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenAssuranceLevel() {
        return tokenAssuranceLevel;
    }

    /**
     * Sets the value of the tokenAssuranceLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenAssuranceLevel(String value) {
        this.tokenAssuranceLevel = value;
    }

    /**
     * Gets the value of the reserved property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReserved() {
        return reserved;
    }

    /**
     * Sets the value of the reserved property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReserved(String value) {
        this.reserved = value;
    }

}
