//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.04 at 05:39:40 AM UTC 
//


package com.firstdata.cmpwsapi.schemas.cmpmsg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExtensionRecords complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtensionRecords"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="EAX001" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}EAX001" minOccurs="0"/&gt;
 *         &lt;element name="EAX002" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}EAX002" minOccurs="0"/&gt;
 *         &lt;element name="EAX003" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}EAX003" minOccurs="0"/&gt;
 *         &lt;element name="EAX004" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}EAX004" minOccurs="0"/&gt;
 *         &lt;element name="EAX005" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}EAX005" minOccurs="0"/&gt;
 *         &lt;element name="EMC001" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}EMC001" minOccurs="0"/&gt;
 *         &lt;element name="EMC002" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}EMC002" minOccurs="0"/&gt;
 *         &lt;element name="EVI001" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}EVI001" minOccurs="0"/&gt;
 *         &lt;element name="EVI002" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}EVI002" minOccurs="0"/&gt;
 *         &lt;element name="EVI004" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}EVI004" minOccurs="0"/&gt;
 *         &lt;element name="EDI002" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}EDI002" minOccurs="0"/&gt;
 *         &lt;element name="EDI003" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}EDI003" minOccurs="0"/&gt;
 *         &lt;element name="EDI004" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}EDI004" minOccurs="0"/&gt;
 *         &lt;element name="EBL001" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}EBL001" minOccurs="0"/&gt;
 *         &lt;element name="EGE001" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}EGE001" minOccurs="0"/&gt;
 *         &lt;element name="EFC001" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}EFC001" minOccurs="0"/&gt;
 *         &lt;element name="ETC001" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}ETC001" minOccurs="0"/&gt;
 *         &lt;element name="ETC002" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}ETC002" minOccurs="0"/&gt;
 *         &lt;element name="EXA001" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}EXA001" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtensionRecords", propOrder = {

})
public class ExtensionRecords {

    @XmlElement(name = "EAX001")
    protected EAX001 eax001;
    @XmlElement(name = "EAX002")
    protected EAX002 eax002;
    @XmlElement(name = "EAX003")
    protected EAX003 eax003;
    @XmlElement(name = "EAX004")
    protected EAX004 eax004;
    @XmlElement(name = "EAX005")
    protected EAX005 eax005;
    @XmlElement(name = "EMC001")
    protected EMC001 emc001;
    @XmlElement(name = "EMC002")
    protected EMC002 emc002;
    @XmlElement(name = "EVI001")
    protected EVI001 evi001;
    @XmlElement(name = "EVI002")
    protected EVI002 evi002;
    @XmlElement(name = "EVI004")
    protected EVI004 evi004;
    @XmlElement(name = "EDI002")
    protected EDI002 edi002;
    @XmlElement(name = "EDI003")
    protected EDI003 edi003;
    @XmlElement(name = "EDI004")
    protected EDI004 edi004;
    @XmlElement(name = "EBL001")
    protected EBL001 ebl001;
    @XmlElement(name = "EGE001")
    protected EGE001 ege001;
    @XmlElement(name = "EFC001")
    protected EFC001 efc001;
    @XmlElement(name = "ETC001")
    protected ETC001 etc001;
    @XmlElement(name = "ETC002")
    protected ETC002 etc002;
    @XmlElement(name = "EXA001")
    protected EXA001 exa001;

    /**
     * Gets the value of the eax001 property.
     * 
     * @return
     *     possible object is
     *     {@link EAX001 }
     *     
     */
    public EAX001 getEAX001() {
        return eax001;
    }

    /**
     * Sets the value of the eax001 property.
     * 
     * @param value
     *     allowed object is
     *     {@link EAX001 }
     *     
     */
    public void setEAX001(EAX001 value) {
        this.eax001 = value;
    }

    /**
     * Gets the value of the eax002 property.
     * 
     * @return
     *     possible object is
     *     {@link EAX002 }
     *     
     */
    public EAX002 getEAX002() {
        return eax002;
    }

    /**
     * Sets the value of the eax002 property.
     * 
     * @param value
     *     allowed object is
     *     {@link EAX002 }
     *     
     */
    public void setEAX002(EAX002 value) {
        this.eax002 = value;
    }

    /**
     * Gets the value of the eax003 property.
     * 
     * @return
     *     possible object is
     *     {@link EAX003 }
     *     
     */
    public EAX003 getEAX003() {
        return eax003;
    }

    /**
     * Sets the value of the eax003 property.
     * 
     * @param value
     *     allowed object is
     *     {@link EAX003 }
     *     
     */
    public void setEAX003(EAX003 value) {
        this.eax003 = value;
    }

    /**
     * Gets the value of the eax004 property.
     * 
     * @return
     *     possible object is
     *     {@link EAX004 }
     *     
     */
    public EAX004 getEAX004() {
        return eax004;
    }

    /**
     * Sets the value of the eax004 property.
     * 
     * @param value
     *     allowed object is
     *     {@link EAX004 }
     *     
     */
    public void setEAX004(EAX004 value) {
        this.eax004 = value;
    }

    /**
     * Gets the value of the eax005 property.
     * 
     * @return
     *     possible object is
     *     {@link EAX005 }
     *     
     */
    public EAX005 getEAX005() {
        return eax005;
    }

    /**
     * Sets the value of the eax005 property.
     * 
     * @param value
     *     allowed object is
     *     {@link EAX005 }
     *     
     */
    public void setEAX005(EAX005 value) {
        this.eax005 = value;
    }

    /**
     * Gets the value of the emc001 property.
     * 
     * @return
     *     possible object is
     *     {@link EMC001 }
     *     
     */
    public EMC001 getEMC001() {
        return emc001;
    }

    /**
     * Sets the value of the emc001 property.
     * 
     * @param value
     *     allowed object is
     *     {@link EMC001 }
     *     
     */
    public void setEMC001(EMC001 value) {
        this.emc001 = value;
    }

    /**
     * Gets the value of the emc002 property.
     * 
     * @return
     *     possible object is
     *     {@link EMC002 }
     *     
     */
    public EMC002 getEMC002() {
        return emc002;
    }

    /**
     * Sets the value of the emc002 property.
     * 
     * @param value
     *     allowed object is
     *     {@link EMC002 }
     *     
     */
    public void setEMC002(EMC002 value) {
        this.emc002 = value;
    }

    /**
     * Gets the value of the evi001 property.
     * 
     * @return
     *     possible object is
     *     {@link EVI001 }
     *     
     */
    public EVI001 getEVI001() {
        return evi001;
    }

    /**
     * Sets the value of the evi001 property.
     * 
     * @param value
     *     allowed object is
     *     {@link EVI001 }
     *     
     */
    public void setEVI001(EVI001 value) {
        this.evi001 = value;
    }

    /**
     * Gets the value of the evi002 property.
     * 
     * @return
     *     possible object is
     *     {@link EVI002 }
     *     
     */
    public EVI002 getEVI002() {
        return evi002;
    }

    /**
     * Sets the value of the evi002 property.
     * 
     * @param value
     *     allowed object is
     *     {@link EVI002 }
     *     
     */
    public void setEVI002(EVI002 value) {
        this.evi002 = value;
    }

    /**
     * Gets the value of the evi004 property.
     * 
     * @return
     *     possible object is
     *     {@link EVI004 }
     *     
     */
    public EVI004 getEVI004() {
        return evi004;
    }

    /**
     * Sets the value of the evi004 property.
     * 
     * @param value
     *     allowed object is
     *     {@link EVI004 }
     *     
     */
    public void setEVI004(EVI004 value) {
        this.evi004 = value;
    }

    /**
     * Gets the value of the edi002 property.
     * 
     * @return
     *     possible object is
     *     {@link EDI002 }
     *     
     */
    public EDI002 getEDI002() {
        return edi002;
    }

    /**
     * Sets the value of the edi002 property.
     * 
     * @param value
     *     allowed object is
     *     {@link EDI002 }
     *     
     */
    public void setEDI002(EDI002 value) {
        this.edi002 = value;
    }

    /**
     * Gets the value of the edi003 property.
     * 
     * @return
     *     possible object is
     *     {@link EDI003 }
     *     
     */
    public EDI003 getEDI003() {
        return edi003;
    }

    /**
     * Sets the value of the edi003 property.
     * 
     * @param value
     *     allowed object is
     *     {@link EDI003 }
     *     
     */
    public void setEDI003(EDI003 value) {
        this.edi003 = value;
    }

    /**
     * Gets the value of the edi004 property.
     * 
     * @return
     *     possible object is
     *     {@link EDI004 }
     *     
     */
    public EDI004 getEDI004() {
        return edi004;
    }

    /**
     * Sets the value of the edi004 property.
     * 
     * @param value
     *     allowed object is
     *     {@link EDI004 }
     *     
     */
    public void setEDI004(EDI004 value) {
        this.edi004 = value;
    }

    /**
     * Gets the value of the ebl001 property.
     * 
     * @return
     *     possible object is
     *     {@link EBL001 }
     *     
     */
    public EBL001 getEBL001() {
        return ebl001;
    }

    /**
     * Sets the value of the ebl001 property.
     * 
     * @param value
     *     allowed object is
     *     {@link EBL001 }
     *     
     */
    public void setEBL001(EBL001 value) {
        this.ebl001 = value;
    }

    /**
     * Gets the value of the ege001 property.
     * 
     * @return
     *     possible object is
     *     {@link EGE001 }
     *     
     */
    public EGE001 getEGE001() {
        return ege001;
    }

    /**
     * Sets the value of the ege001 property.
     * 
     * @param value
     *     allowed object is
     *     {@link EGE001 }
     *     
     */
    public void setEGE001(EGE001 value) {
        this.ege001 = value;
    }

    /**
     * Gets the value of the efc001 property.
     * 
     * @return
     *     possible object is
     *     {@link EFC001 }
     *     
     */
    public EFC001 getEFC001() {
        return efc001;
    }

    /**
     * Sets the value of the efc001 property.
     * 
     * @param value
     *     allowed object is
     *     {@link EFC001 }
     *     
     */
    public void setEFC001(EFC001 value) {
        this.efc001 = value;
    }

    /**
     * Gets the value of the etc001 property.
     * 
     * @return
     *     possible object is
     *     {@link ETC001 }
     *     
     */
    public ETC001 getETC001() {
        return etc001;
    }

    /**
     * Sets the value of the etc001 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ETC001 }
     *     
     */
    public void setETC001(ETC001 value) {
        this.etc001 = value;
    }

    /**
     * Gets the value of the etc002 property.
     * 
     * @return
     *     possible object is
     *     {@link ETC002 }
     *     
     */
    public ETC002 getETC002() {
        return etc002;
    }

    /**
     * Sets the value of the etc002 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ETC002 }
     *     
     */
    public void setETC002(ETC002 value) {
        this.etc002 = value;
    }

    /**
     * Gets the value of the exa001 property.
     * 
     * @return
     *     possible object is
     *     {@link EXA001 }
     *     
     */
    public EXA001 getEXA001() {
        return exa001;
    }

    /**
     * Sets the value of the exa001 property.
     * 
     * @param value
     *     allowed object is
     *     {@link EXA001 }
     *     
     */
    public void setEXA001(EXA001 value) {
        this.exa001 = value;
    }

}
