//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.04 at 05:39:40 AM UTC 
//


package com.firstdata.cmpwsapi.schemas.cmpmsg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FormattedAddressRecords complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FormattedAddressRecords"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="BillToAddress" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}BillToAddress" minOccurs="0"/&gt;
 *         &lt;element name="BillToTelephone" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}BillToTelephone" minOccurs="0"/&gt;
 *         &lt;element name="ShipToAddress" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}ShipToAddress" minOccurs="0"/&gt;
 *         &lt;element name="ShipToTelephone" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}ShipToTelephone" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FormattedAddressRecords", propOrder = {

})
public class FormattedAddressRecords {

    @XmlElement(name = "BillToAddress")
    protected BillToAddress billToAddress;
    @XmlElement(name = "BillToTelephone")
    protected BillToTelephone billToTelephone;
    @XmlElement(name = "ShipToAddress")
    protected ShipToAddress shipToAddress;
    @XmlElement(name = "ShipToTelephone")
    protected ShipToTelephone shipToTelephone;

    /**
     * Gets the value of the billToAddress property.
     * 
     * @return
     *     possible object is
     *     {@link BillToAddress }
     *     
     */
    public BillToAddress getBillToAddress() {
        return billToAddress;
    }

    /**
     * Sets the value of the billToAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillToAddress }
     *     
     */
    public void setBillToAddress(BillToAddress value) {
        this.billToAddress = value;
    }

    /**
     * Gets the value of the billToTelephone property.
     * 
     * @return
     *     possible object is
     *     {@link BillToTelephone }
     *     
     */
    public BillToTelephone getBillToTelephone() {
        return billToTelephone;
    }

    /**
     * Sets the value of the billToTelephone property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillToTelephone }
     *     
     */
    public void setBillToTelephone(BillToTelephone value) {
        this.billToTelephone = value;
    }

    /**
     * Gets the value of the shipToAddress property.
     * 
     * @return
     *     possible object is
     *     {@link ShipToAddress }
     *     
     */
    public ShipToAddress getShipToAddress() {
        return shipToAddress;
    }

    /**
     * Sets the value of the shipToAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipToAddress }
     *     
     */
    public void setShipToAddress(ShipToAddress value) {
        this.shipToAddress = value;
    }

    /**
     * Gets the value of the shipToTelephone property.
     * 
     * @return
     *     possible object is
     *     {@link ShipToTelephone }
     *     
     */
    public ShipToTelephone getShipToTelephone() {
        return shipToTelephone;
    }

    /**
     * Sets the value of the shipToTelephone property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipToTelephone }
     *     
     */
    public void setShipToTelephone(ShipToTelephone value) {
        this.shipToTelephone = value;
    }

}
