//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.04 at 05:39:40 AM UTC 
//


package com.firstdata.cmpwsapi.schemas.cmpmsg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InformationRecords complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InformationRecords"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="IOI" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}IOI" minOccurs="0"/&gt;
 *         &lt;element name="IPI001" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}IPI001" minOccurs="0"/&gt;
 *         &lt;element name="IAA" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}IAA" minOccurs="0"/&gt;
 *         &lt;element name="IGS" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}IGS" minOccurs="0"/&gt;
 *         &lt;element name="ISS001" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}ISS001" minOccurs="0"/&gt;
 *         &lt;element name="IPTS" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}IPTS" minOccurs="0"/&gt;
 *         &lt;element name="ICD001" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}ICD001" minOccurs="0"/&gt;
 *         &lt;element name="ICN001" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}ICN001" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InformationRecords", propOrder = {

})
public class InformationRecords {

    @XmlElement(name = "IOI")
    protected IOI ioi;
    @XmlElement(name = "IPI001")
    protected IPI001 ipi001;
    @XmlElement(name = "IAA")
    protected IAA iaa;
    @XmlElement(name = "IGS")
    protected IGS igs;
    @XmlElement(name = "ISS001")
    protected ISS001 iss001;
    @XmlElement(name = "IPTS")
    protected IPTS ipts;
    @XmlElement(name = "ICD001")
    protected ICD001 icd001;
    @XmlElement(name = "ICN001")
    protected ICN001 icn001;

    /**
     * Gets the value of the ioi property.
     * 
     * @return
     *     possible object is
     *     {@link IOI }
     *     
     */
    public IOI getIOI() {
        return ioi;
    }

    /**
     * Sets the value of the ioi property.
     * 
     * @param value
     *     allowed object is
     *     {@link IOI }
     *     
     */
    public void setIOI(IOI value) {
        this.ioi = value;
    }

    /**
     * Gets the value of the ipi001 property.
     * 
     * @return
     *     possible object is
     *     {@link IPI001 }
     *     
     */
    public IPI001 getIPI001() {
        return ipi001;
    }

    /**
     * Sets the value of the ipi001 property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPI001 }
     *     
     */
    public void setIPI001(IPI001 value) {
        this.ipi001 = value;
    }

    /**
     * Gets the value of the iaa property.
     * 
     * @return
     *     possible object is
     *     {@link IAA }
     *     
     */
    public IAA getIAA() {
        return iaa;
    }

    /**
     * Sets the value of the iaa property.
     * 
     * @param value
     *     allowed object is
     *     {@link IAA }
     *     
     */
    public void setIAA(IAA value) {
        this.iaa = value;
    }

    /**
     * Gets the value of the igs property.
     * 
     * @return
     *     possible object is
     *     {@link IGS }
     *     
     */
    public IGS getIGS() {
        return igs;
    }

    /**
     * Sets the value of the igs property.
     * 
     * @param value
     *     allowed object is
     *     {@link IGS }
     *     
     */
    public void setIGS(IGS value) {
        this.igs = value;
    }

    /**
     * Gets the value of the iss001 property.
     * 
     * @return
     *     possible object is
     *     {@link ISS001 }
     *     
     */
    public ISS001 getISS001() {
        return iss001;
    }

    /**
     * Sets the value of the iss001 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISS001 }
     *     
     */
    public void setISS001(ISS001 value) {
        this.iss001 = value;
    }

    /**
     * Gets the value of the ipts property.
     * 
     * @return
     *     possible object is
     *     {@link IPTS }
     *     
     */
    public IPTS getIPTS() {
        return ipts;
    }

    /**
     * Sets the value of the ipts property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPTS }
     *     
     */
    public void setIPTS(IPTS value) {
        this.ipts = value;
    }

    /**
     * Gets the value of the icd001 property.
     * 
     * @return
     *     possible object is
     *     {@link ICD001 }
     *     
     */
    public ICD001 getICD001() {
        return icd001;
    }

    /**
     * Sets the value of the icd001 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ICD001 }
     *     
     */
    public void setICD001(ICD001 value) {
        this.icd001 = value;
    }

    /**
     * Gets the value of the icn001 property.
     * 
     * @return
     *     possible object is
     *     {@link ICN001 }
     *     
     */
    public ICN001 getICN001() {
        return icn001;
    }

    /**
     * Sets the value of the icn001 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ICN001 }
     *     
     */
    public void setICN001(ICN001 value) {
        this.icn001 = value;
    }

}
