//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.04 at 05:39:40 AM UTC 
//


package com.firstdata.cmpwsapi.schemas.cmpmsg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MCPPK3 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MCPPK3"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ProductRecordSequenceNumber"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
 *               &lt;minInclusive value="01"/&gt;
 *               &lt;maxInclusive value="75"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="MiscExpenseDescriptor1"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="50"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="MiscExpenseAmount1" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[0-9]{0,12}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MCPPK3", propOrder = {
    "productRecordSequenceNumber",
    "miscExpenseDescriptor1",
    "miscExpenseAmount1"
})
public class MCPPK3 {

    @XmlElement(name = "ProductRecordSequenceNumber")
    protected int productRecordSequenceNumber;
    @XmlElement(name = "MiscExpenseDescriptor1", required = true)
    protected String miscExpenseDescriptor1;
    @XmlElement(name = "MiscExpenseAmount1")
    protected String miscExpenseAmount1;

    /**
     * Gets the value of the productRecordSequenceNumber property.
     * 
     */
    public int getProductRecordSequenceNumber() {
        return productRecordSequenceNumber;
    }

    /**
     * Sets the value of the productRecordSequenceNumber property.
     * 
     */
    public void setProductRecordSequenceNumber(int value) {
        this.productRecordSequenceNumber = value;
    }

    /**
     * Gets the value of the miscExpenseDescriptor1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiscExpenseDescriptor1() {
        return miscExpenseDescriptor1;
    }

    /**
     * Sets the value of the miscExpenseDescriptor1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiscExpenseDescriptor1(String value) {
        this.miscExpenseDescriptor1 = value;
    }

    /**
     * Gets the value of the miscExpenseAmount1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiscExpenseAmount1() {
        return miscExpenseAmount1;
    }

    /**
     * Sets the value of the miscExpenseAmount1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiscExpenseAmount1(String value) {
        this.miscExpenseAmount1 = value;
    }

}
