//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.04 at 05:39:40 AM UTC 
//


package com.firstdata.cmpwsapi.schemas.cmpmsg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MW complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MW"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MasterPassIndicator" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="N"/&gt;
 *               &lt;enumeration value="U"/&gt;
 *               &lt;enumeration value="S"/&gt;
 *               &lt;enumeration value="A"/&gt;
 *               &lt;enumeration value="I"/&gt;
 *               &lt;enumeration value="M"/&gt;
 *               &lt;enumeration value=" "/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="WalletProgramID" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="101"/&gt;
 *               &lt;enumeration value="102"/&gt;
 *               &lt;enumeration value="103"/&gt;
 *               &lt;enumeration value="216"/&gt;
 *               &lt;enumeration value="217"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MW", propOrder = {
    "masterPassIndicator",
    "walletProgramID"
})
public class MW {

    @XmlElement(name = "MasterPassIndicator")
    protected String masterPassIndicator;
    @XmlElement(name = "WalletProgramID")
    protected String walletProgramID;

    /**
     * Gets the value of the masterPassIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasterPassIndicator() {
        return masterPassIndicator;
    }

    /**
     * Sets the value of the masterPassIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterPassIndicator(String value) {
        this.masterPassIndicator = value;
    }

    /**
     * Gets the value of the walletProgramID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWalletProgramID() {
        return walletProgramID;
    }

    /**
     * Sets the value of the walletProgramID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWalletProgramID(String value) {
        this.walletProgramID = value;
    }

}
