//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.04 at 05:39:40 AM UTC 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://firstdata.com/cmpwsapi/schemas/cmpmsg", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.firstdata.cmpwsapi.schemas.cmpmsg;
