//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.04 at 05:39:40 AM UTC 
//


package com.firstdata.cmpwsapi.schemas.cmpmsg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PI complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PI"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CustomerDOB" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[0-9]{8}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CustomerSSN" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[0-9]{0,9}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CurrencyTGHAI" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="036"/&gt;
 *               &lt;enumeration value="826"/&gt;
 *               &lt;enumeration value="124"/&gt;
 *               &lt;enumeration value="208"/&gt;
 *               &lt;enumeration value="978"/&gt;
 *               &lt;enumeration value="344"/&gt;
 *               &lt;enumeration value="392"/&gt;
 *               &lt;enumeration value="554"/&gt;
 *               &lt;enumeration value="578"/&gt;
 *               &lt;enumeration value="702"/&gt;
 *               &lt;enumeration value="710"/&gt;
 *               &lt;enumeration value="752"/&gt;
 *               &lt;enumeration value="756"/&gt;
 *               &lt;enumeration value="840"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="GHAnnualIncome" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[0-9]{0,10}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CustomerResidenceStatus" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="O"/&gt;
 *               &lt;enumeration value="R"/&gt;
 *               &lt;enumeration value="X"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CustomerYearsAtResidence" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[0-9]{0,2}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CustomerYearsAtEmployer" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[0-9]{0,2}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CustomerCheckingAccount" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CustomerSavingsAccount" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PI", propOrder = {
    "customerDOB",
    "customerSSN",
    "currencyTGHAI",
    "ghAnnualIncome",
    "customerResidenceStatus",
    "customerYearsAtResidence",
    "customerYearsAtEmployer",
    "customerCheckingAccount",
    "customerSavingsAccount"
})
@XmlSeeAlso({
    IPI001 .class
})
public class PI {

    @XmlElement(name = "CustomerDOB")
    protected String customerDOB;
    @XmlElement(name = "CustomerSSN")
    protected String customerSSN;
    @XmlElement(name = "CurrencyTGHAI")
    protected String currencyTGHAI;
    @XmlElement(name = "GHAnnualIncome")
    protected String ghAnnualIncome;
    @XmlElement(name = "CustomerResidenceStatus")
    protected String customerResidenceStatus;
    @XmlElement(name = "CustomerYearsAtResidence")
    protected String customerYearsAtResidence;
    @XmlElement(name = "CustomerYearsAtEmployer")
    protected String customerYearsAtEmployer;
    @XmlElement(name = "CustomerCheckingAccount")
    protected String customerCheckingAccount;
    @XmlElement(name = "CustomerSavingsAccount")
    protected String customerSavingsAccount;

    /**
     * Gets the value of the customerDOB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerDOB() {
        return customerDOB;
    }

    /**
     * Sets the value of the customerDOB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerDOB(String value) {
        this.customerDOB = value;
    }

    /**
     * Gets the value of the customerSSN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerSSN() {
        return customerSSN;
    }

    /**
     * Sets the value of the customerSSN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerSSN(String value) {
        this.customerSSN = value;
    }

    /**
     * Gets the value of the currencyTGHAI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyTGHAI() {
        return currencyTGHAI;
    }

    /**
     * Sets the value of the currencyTGHAI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyTGHAI(String value) {
        this.currencyTGHAI = value;
    }

    /**
     * Gets the value of the ghAnnualIncome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGHAnnualIncome() {
        return ghAnnualIncome;
    }

    /**
     * Sets the value of the ghAnnualIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGHAnnualIncome(String value) {
        this.ghAnnualIncome = value;
    }

    /**
     * Gets the value of the customerResidenceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerResidenceStatus() {
        return customerResidenceStatus;
    }

    /**
     * Sets the value of the customerResidenceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerResidenceStatus(String value) {
        this.customerResidenceStatus = value;
    }

    /**
     * Gets the value of the customerYearsAtResidence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerYearsAtResidence() {
        return customerYearsAtResidence;
    }

    /**
     * Sets the value of the customerYearsAtResidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerYearsAtResidence(String value) {
        this.customerYearsAtResidence = value;
    }

    /**
     * Gets the value of the customerYearsAtEmployer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerYearsAtEmployer() {
        return customerYearsAtEmployer;
    }

    /**
     * Sets the value of the customerYearsAtEmployer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerYearsAtEmployer(String value) {
        this.customerYearsAtEmployer = value;
    }

    /**
     * Gets the value of the customerCheckingAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerCheckingAccount() {
        return customerCheckingAccount;
    }

    /**
     * Sets the value of the customerCheckingAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerCheckingAccount(String value) {
        this.customerCheckingAccount = value;
    }

    /**
     * Gets the value of the customerSavingsAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerSavingsAccount() {
        return customerSavingsAccount;
    }

    /**
     * Sets the value of the customerSavingsAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerSavingsAccount(String value) {
        this.customerSavingsAccount = value;
    }

}
