//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.04 at 05:39:40 AM UTC 
//


package com.firstdata.cmpwsapi.schemas.cmpmsg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PPB001 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PPB001"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PB" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}PB"/&gt;
 *         &lt;element name="PBPA" type="{http://firstdata.com/cmpwsapi/schemas/cmpmsg}PBPA"/&gt;
 *         &lt;element name="Reserved" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="89"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PPB001", propOrder = {
    "pb",
    "pbpa",
    "reserved"
})
public class PPB001 {

    @XmlElement(name = "PB", required = true)
    protected PB pb;
    @XmlElement(name = "PBPA", required = true)
    protected PBPA pbpa;
    @XmlElement(name = "Reserved")
    protected String reserved;

    /**
     * Gets the value of the pb property.
     * 
     * @return
     *     possible object is
     *     {@link PB }
     *     
     */
    public PB getPB() {
        return pb;
    }

    /**
     * Sets the value of the pb property.
     * 
     * @param value
     *     allowed object is
     *     {@link PB }
     *     
     */
    public void setPB(PB value) {
        this.pb = value;
    }

    /**
     * Gets the value of the pbpa property.
     * 
     * @return
     *     possible object is
     *     {@link PBPA }
     *     
     */
    public PBPA getPBPA() {
        return pbpa;
    }

    /**
     * Sets the value of the pbpa property.
     * 
     * @param value
     *     allowed object is
     *     {@link PBPA }
     *     
     */
    public void setPBPA(PBPA value) {
        this.pbpa = value;
    }

    /**
     * Gets the value of the reserved property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReserved() {
        return reserved;
    }

    /**
     * Sets the value of the reserved property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReserved(String value) {
        this.reserved = value;
    }

}
